### ISSUE TITLE
How to init mardownx for custom html containers

### ISSUE THREAD

**Issue by lolorama** [neutronX/django-markdownx#62]
Is there any way to connect "editor" and "preview" containers separately from the parent?

I've found out that markdownx.js triggers lookup for ".markdownx" container with ".markdownx-preview" and "markdownx-editor". 

Is there any way to prevent this and manually setup ".markdownx-preview" and "markdownx-editor" with different parents for both of them?

**Comment by adi-** [comment]
What exactly you want to achieve?

If you want an extra container for `.markdownx-preview` and `.markdownx-editor` you can alter default template. But I guess you already checked that...

**Comment by xenatisch** [comment]
Shall we assume that this issue is resolved?

**Comment by lolorama** [comment]
What I was looking for is initializing markdownx like this (When we can't specify .markdownx class to parent element):

```
<body>
    <div class="container">
        <div class="markdownx-preview"></div>
    </div>
    <div class="sidebar">
        <div class="markdownx-editor"></div>
    </div>
</body>
```

I've not resolved this in such way and have to use different layout like this:

```
<div class="container">
    <div class="markdownx">
        <div class="markdownx-preview"></div>
        <div class="markdownx-editor"></div>
    </div>
</div>
```
